site_name: Terraform
site_url: https://github.com/celsonery/terraform-docs
theme: 
  name: readthedocs
  highlightjs: true
  locale: pt_BR
nav:
  - Terraform: 
    - Intalação: terraform/01-instalacao.md
  - AWS:
    - Criar conta na AWS: aws/01-criar-conta-aws.md
    - Conta IAM Terraform: aws/02-criar-conta-iam.md
    - Grupo IAM e permissões: aws/03-criar-grupo-permissoes.md
    - Dependências: terraform/02-dependencias.md
    - Variáveis: terraform/03-variaveis.md
    - Scripts: terraform/04-scripts.md
    - Outputs: terraform/05-outputs.md
    - Reorganização dos arquivos: terraform/06-reorganizar.md
  - GCP:
    - Criar conta na GCP:  gcp/01-criar-conta-gcp.md
